version: "3"
services:
  app1:
    build: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
  app2:
    build: .
    ports:
      - "9000:9000"
    networks:
      - mynetwork

networks:
  mynetwork:
